# Generated by Django 5.2.17 on 2026-08-10 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('employee_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('mobile_number', models.CharField(max_length=15, unique=True)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('OPERATOR', 'Pump Operator'), ('DRIVER', 'Truck Driver')], default='DRIVER', max_length=20)),
                ('approval_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pump',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('contact_number', models.CharField(blank=True, max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(blank=True, limit_choices_to={'role': 'OPERATOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_pumps', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_number', models.CharField(max_length=20, unique=True)),
                ('fuel_type', models.CharField(choices=[('DIESEL', 'Diesel'), ('PETROL', 'Petrol')], default='DIESEL', max_length=10)),
                ('capacity_liters', models.PositiveIntegerField(blank=True, help_text='Maximum fuel tank capacity', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(blank=True, limit_choices_to={'role': 'DRIVER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trucks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FuelRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(max_length=20, unique=True)),
                ('fuel_type', models.CharField(choices=[('DIESEL', 'Diesel'), ('PETROL', 'Petrol')], max_length=10)),
                ('requested_liters', models.DecimalField(decimal_places=2, max_digits=6)),
                ('approved_liters', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('VERIFIED', 'Verified'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('driver', models.ForeignKey(limit_choices_to={'role': 'DRIVER'}, on_delete=django.db.models.deletion.PROTECT, related_name='fuel_requests', to=settings.AUTH_USER_MODEL)),
                ('operator', models.ForeignKey(blank=True, limit_choices_to={'role': 'OPERATOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_fuel_requests', to=settings.AUTH_USER_MODEL)),
                ('pump', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fuel_requests', to='fuel.pump')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fuel_requests', to='fuel.truck')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_image', models.ImageField(blank=True, null=True, upload_to='vehicle_verification/')),
                ('ocr_number', models.CharField(blank=True, max_length=20, null=True)),
                ('manual_number', models.CharField(blank=True, max_length=20, null=True)),
                ('verification_method', models.CharField(blank=True, choices=[('OCR', 'OCR'), ('MANUAL', 'Manual')], max_length=10, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fuel_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_verification', to='fuel.fuelrequest')),
                ('verified_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'OPERATOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_verifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
