# Generated by Django 5.0.14 on 2026-08-13 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pump',
            name='operator',
        ),
        migrations.CreateModel(
            name='PumpOperator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('operator', models.OneToOneField(limit_choices_to={'role': 'OPERATOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='pump_assignment', to=settings.AUTH_USER_MODEL)),
                ('pump', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pump_operators', to='fuel.pump')),
            ],
        ),
        migrations.AddField(
            model_name='pump',
            name='operators',
            field=models.ManyToManyField(blank=True, related_name='assigned_pumps', through='fuel.PumpOperator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='pumpoperator',
            constraint=models.UniqueConstraint(fields=('operator',), name='unique_operator_one_pump'),
        ),
    ]
